[package]
name = "simd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0"

[dev-dependencies]
criterion = "0"

[[bench]]
name = "vfloat"
harness = false